Parsing of parameters from ./Allrun, initial omniscent script

diff --git a/simulation/Allrun b/simulation/Allrun
--- a/simulation/Allrun
+++ b/simulation/Allrun
@@ -43,24 +43,216 @@ cp -f \
     "$FOAM_RUN"/freight_train_CFD/objects/backInternalWall.stl \
     constant/triSurface/
 
-# Define the rotation angle to be used for the simulation: in this case, read the second argument passed to the script.
-# The first argument defines the flag to actually rotate the simulation
-# If no parameters are passed, the default value for the flag is false and the angle is 0
-echo "The angle is ${2:-0}"
-echo "The angulation flag is ${1:-false}"
+# ----------------------------* PARAMETER PARSING *--------------------------
+# Define some default values
+angulation_flag="false"
+angle_value=0
+gallery_included="false"
+rotated_refinement="false"
 
-# Replace the placeholder in the angulationParameters_0 file with the actual value and save the result in the angulationParameters file
-sed "s/ANGULATION_ANGLE_PLACEHOLDER/${2:-0}/g" "0.orig/include/angulationParameters_0"> \0.orig/include/angulationParameters
-sed -i "s/ANGULATION_FLAG_PLACEHOLDER/${1:-false}/g" "0.orig/include/angulationParameters" 
+OPTSTRING="av:gor:t:"
 
-# The gallery is included in the simulation according to the third argument passed to the script: if no parameter is passed, the default value is false
-echo "The gallery is included in the simulation: ${3:-false}"
-sed -i "s/GALLERY_FLAG_PLACEHOLDER/${3:-false}/g" "0.orig/include/angulationParameters"
+# Copy the original refinementParameters_0 (template) file to the refinementParameters file
+cp 0.orig/include/refinementParameters_0 0.orig/include/refinementParameters
+cp 0.orig/include/angulationParameters_0 0.orig/include/angulationParameters
+cp 0.orig/include/blockParameters_0 0.orig/include/blockParameters
+
+# Parse the arguments passed to the script
+while getopts ${OPTSTRING} opt; do
+  case $opt in
+    a) 
+        angulation_flag="true"
+        echo "The angulation flag is set to: $angulation_flag"
+         
+    ;;
+    v) 
+        angle_value="$OPTARG"
+        echo "The angle is $angle_value"
+    ;;
+    g) 
+        gallery_included="true"
+        echo "The gallery is included in the simulation: $gallery_included"
+    ;;
+    o) 
+        rotated_refinement="true"
+        echo "The refinement boxes are rotated: $rotated_refinement"
+    ;;
+    r) # This case is used to parse the refinement box parameters
+        # We need to parse as input a string with the following format:
+        #"{REFINEMENT_BOX_N,REFINEMENT_LEVEL_N,(SPAN_N_x SPAN_N_y SPAN_N_z),orig_N0_x,oirg_N0_z},..."
+        # example: "{{true,2,(0.1 0.1 0.1),0,0},{false,1,(0.1 0.1 0.1),0,0}}"
+        # where N is the number of the refinement box
+        # and orig_N0_x and orig_N0_z are the coordinates of the origin of the refinement box
+        # and SPAN_N is the span of the refinement box
+        # The string is parsed and the values are saved in the refinementParameters file
+        # by replacing the placeholders with the actual values
+
+        echo "=========================* REFINEMENT - BOXES *========================="
+        echo "The refinement boxes included in the simulation at hand  are:"
+
+        # remove the outer "{" and "}" from the string
+        OPTARG=${OPTARG//[\{\}]/}
+
+        # Parse the string, split it by the ; character and save the result in an array.
+        # Then iterate over each element of the array and extract the values of the refinement box represented by the element of the array
+        # Note that the index of the array is the number of the refinement box, while the first token extracted from each element of the array
+        # is a flag to indicate whether the refinement box is included in the simulation or not.
+        IFS=',' read -ra refinementBoxes <<< "$OPTARG"
+        for i in "${!refinementBoxes[@]}"; do
+            IFS=',' read -ra refinementBox <<< "${refinementBoxes[i]//[\{\}]/}"
+            echo "REFINEMENT_BOX_$i is included in the simulation: ${refinementBox[0]}"
+            echo "Refinement level for box $i is: ${refinementBox[1]}"
+            echo "Span for box $i is: ${refinementBox[2]}"
+            echo "Origin_x for box $i is: ${refinementBox[3]}"
+            echo "Origin_z for box $i is: ${refinementBox[4]}"
+
+            # Replace the placeholders in the refinementParameters file with the actual values and save the result in the refinementParameters file
+            sed -i "s/REFINEMENT_BOX_PLACEHOLDER_$i/${refinementBox[0]}/g" "0.orig/include/refinementParameters"
+            sed -i "s/REFINEMENT_LEVEL_PLACEHOLDER_$i/${refinementBox[1]}/g" "0.orig/include/refinementParameters"
+            sed -i "s/SPAN_PLACEHOLDER_$i/${refinementBox[2]}/g" "0.orig/include/refinementParameters"
+            sed -i "s/ORIG_X_PLACEHOLDER_$i/${refinementBox[3]}/g" "0.orig/include/refinementParameters"
+            sed -i "s/ORIG_Z_PLACEHOLDER_$i/${refinementBox[4]}/g" "0.orig/include/refinementParameters"
+        done
+
+        # In case a refinement box is excluded from the simulation, (refinementBoxes[i] is not in the refinementBoxes array),
+        # we need to replace the placeholders in the refinementParameters file with some default values:
+        # there are up to 4 refinement boxes in the simulation
+
+        for i in {0..3}; do
+            if [ -z "${refinementBoxes[i]}" ]; then
+                echo "${refinementBoxes[i]}"
+                echo "REFINEMENT_BOX_$i is included in the simulation: false  --- NO DEFINITION GIVEN"
+                # Replace the placeholders in the refinementParameters file with the actual values and save the result in the refinementParameters file
+                sed -i "s/REFINEMENT_BOX_PLACEHOLDER_$i/false/g" "0.orig/include/refinementParameters"
+                sed -i "s/REFINEMENT_LEVEL_PLACEHOLDER_$i/1/g" "0.orig/include/refinementParameters"
+                sed -i "s/SPAN_PLACEHOLDER_$i/(0.1 0.1 0.1)/g" "0.orig/include/refinementParameters"
+                sed -i "s/ORIG_X_PLACEHOLDER_$i/0/g" "0.orig/include/refinementParameters"
+                sed -i "s/ORIG_Z_PLACEHOLDER_$i/0/g" "0.orig/include/refinementParameters"
+            fi
+        done
+
+        echo "=============================================================="
+    ;;
+    t)  # The option lets insert the parameters to define eventual refinement at a certain distance from the train
+        # The string is parsed and the values are saved in the refinementParameters file
+        # by replacing the placeholders with the actual values
+        # The format of the string is the following:
+        # {REFINEMENT_TRAIN_PLACHOLDER; REFINEMENT_DISTANCE_PLACEHOLDER, REFINEMENT_LEVEL_TRAIN_PLACEHOLDER}
+        echo "=========================* REFINEMENT - TRAIN *========================="
+
+        IFS=',' read -ra refinementTrain <<< "$OPTARG//[\{\}]/}"
+        echo " Refinement of the train is included in the simulation: ${refinementTrain[0]}"
+        echo " Refinement distance from the train is: ${refinementTrain[1]}"
+        echo " Refinement level for the train is: ${refinementTrain[2]}"
+
+        # Replace the placeholders in the refinementParameters file with the actual values and save the result in the refinementParameters file
+        sed -i "s/REFINEMENT_TRAIN_PLACEHOLDER/${refinementTrain[0]}/g" "0.orig/include/refinementParameters"
+        sed -i "s/REFINEMENT_DISTANCE_PLACEHOLDER/${refinementTrain[1]}/g" "0.orig/include/refinementParameters"
+        sed -i "s/REFINEMENT_LEVEL_TRAIN_PLACEHOLDER/${refinementTrain[2]}/g" "0.orig/include/refinementParameters"
+
+        echo "=============================================================="
+
+    ;;
+    b)
+        # The option lets insert the parameters to define the dimensions of the block mesh
+        # The string is parsed and the values are saved in the blockMeshDict file
+        # by replacing the placeholders with the actual values
+        # The format of the string is the following ):
+        #{ OUTHER_0, OUTER_1, OUTER_2, ...} 
+        # example: {(-1.268 0 -1.22),(2.812 0 -1.22), (2.812 1.3 -1.22), (-1.268 1.3 -1.22), (-1.268  0 1.22),(2.812  0 1.22) , (2.812  0 1.22), (2.812  0 1.22)}
+        # To run the simulation, the option would require 8 vertices: the correcteness is left to the user.
+        # Yet, some default values are set in the blockMeshDict file if no value for the vertices is given.
+        echo "=========================* BLOCK MESH *========================="
+
+        IFS=',' read -ra blockMeshVertices <<< "$OPTARG//[\{\}]/}"
+        echo "The vertices of the block mesh are: ${blockMeshVertices[@]}"
+        # Replace the placeholders in the blockMeshDict file with the actual values and save the result in the blockMeshDict file
+        for i in "${!blockMeshVertices[@]}"; do
+            sed -i "s/OUTER_PLACEHOLDER_$i/${blockMeshVertices[i]}/g" "0.orig/include/blockParameters"
+        done
+
+        echo "=============================================================="
+
+    ;;
+    c) 
+        # The option lets insert the parameters to define the dimensions for the cells at the lowest level of refinement in the blockMesh
+        # The string is parsed and the values are saved in the blockMeshDict file
+        # by replacing the placeholders with the actual values
+        # The format of the string is the following ):
+        #{ NCELLS_X, NCELLS_Y, NCELLS_Z}
+        #{40, 13, 24}
+
+        echo "=========================* NUM. CELLS *========================="
+
+        IFS=',' read -ra blockMeshCells <<< "$OPTARG//[\{\}]/}"
+        echo "The number of cells at the lowest level of refinement in the block mesh are: ${blockMeshCells[@]}"
+        # Replace the placeholders in the blockMeshDict file with the actual values and save the result in the blockMeshDict file
+        for i in "${!blockMeshCells[@]}"; do
+            sed -i "s/NCELLS_PLACEHOLDER_$i/${blockMeshCells[i]}/g" "0.orig/include/blockParameters"
+        done
+
+        echo "=============================================================="
+
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
+#Handle the case in which no train refinement is required by settin default values in the refinementParameters file
+if [ -z "${refinementTrain[0]}" ]; then
+    echo "Refinement of the train is included in the simulation: false  --- NO DEFINITION GIVEN"
+    # Replace the placeholders in the refinementParameters file with the actual values and save the result in the refinementParameters file
+    sed -i "s/REFINEMENT_TRAIN_PLACEHOLDER/false/g" "0.orig/include/refinementParameters"
+    sed -i "s/REFINEMENT_DISTANCE_PLACEHOLDER/0/g" "0.orig/include/refinementParameters"
+    sed -i "s/REFINEMENT_LEVEL_TRAIN_PLACEHOLDER/1/g" "0.orig/include/refinementParameters"
+fi
+
+#Handle the case in which no block mesh vertices are given by setting default values in the blockMeshDict file
+if [ -z "${blockMeshVertices[0]}" ]; then
+    echo "The vertices of the block mesh are:  --- NO DEFINITION GIVEN"
+    # Replace the placeholders in the blockMeshDict file with the actual values and save the result in the blockMeshDict file
+    
+    sed -i "s/OUTER_PLACEHOLDER_0/(-1.268 0 -1.22)/g" "0.orig/include/blockParameters"
+    sed -i "s/OUTER_PLACEHOLDER_1/(2.812 0 -1.22)/g" "0.orig/include/blockParameters"
+    sed -i "s/OUTER_PLACEHOLDER_2/(2.812 1.3 -1.22)/g" "0.orig/include/blockParameters"
+    sed -i "s/OUTER_PLACEHOLDER_3/(-1.268 1.3 -1.22)/g" "0.orig/include/blockParameters"
+    sed -i "s/OUTER_PLACEHOLDER_4/(-1.268 0 1.22)/g" "0.orig/include/blockParameters"
+    sed -i "s/OUTER_PLACEHOLDER_5/(2.812 0 1.22)/g" "0.orig/include/blockParameters"
+    sed -i "s/OUTER_PLACEHOLDER_6/(2.812 1.3 1.22)/g" "0.orig/include/blockParameters"
+    sed -i "s/OUTER_PLACEHOLDER_7/(-1.268 1.3 1.22)/g" "0.orig/include/blockParameters"
+fi
+
+#Handle the case in which no block mesh cells are given by setting default values in the blockMeshDict file
+if [ -z "${blockMeshCells[0]}" ]; then
+    echo "The number of cells at the lowest level of refinement in the block mesh are:  --- NO DEFINITION GIVEN"
+    # Replace the placeholders in the blockMeshDict file with the actual values and save the result in the blockMeshDict file
+    sed -i "s/NCELLS_PLACEHOLDER_0/40/g" "0.orig/include/blockParameters"
+    sed -i "s/NCELLS_PLACEHOLDER_1/13/g" "0.orig/include/blockParameters"
+    sed -i "s/NCELLS_PLACEHOLDER_2/24/g" "0.orig/include/blockParameters"
+fi
+
+
+
+if [[ $angulation_flag == "false" && $angle_value != "0" ]]; then
+  echo "Error - The angle value is not 0 but the angulation flag is set to false. Please set the angulation flag to true or set the angle value to 0."
+  exit 1
+fi
+
+
+sed -i "s/ANGULATION_FLAG_PLACEHOLDER/$angulation_flag/g" "0.orig/include/angulationParameters"
+sed -i "s/ANGULATION_ANGLE_PLACEHOLDER/$angle_value/g" "0.orig/include/angulationParameters"
+sed -i "s/GALLERY_FLAG_PLACEHOLDER/$gallery_included/g" "0.orig/include/angulationParameters"
+sed -i "s/REFINEMENT_BOXES_ROTATION_FLAG_PLACEHOLDER/$rotated_refinement/g" "0.orig/include/angulationParameters"
+
+##############################################################################
+
+
 # Rotate the box_galleria.stl file by an angle specified in the 0.orig/include/angulationParameters filen along the y axis (also translate the box_galleria.stl file to the origin)
 # Also suppress the output of the surfaceTransformPoints command
 # Do all this only if the gallery is included in the simulation
 
-if [ "${3:-false}" = true ]; then
+if [ "$gallery_included" = true ]; then
     surfaceTransformPoints -translate "(-0.5 0 -0.25)" -rollPitchYaw "(0 ${2:-0} 0)" constant/triSurface/box_galleria.stl constant/triSurface/box_galleria.stl > /dev/null
 
     # Do the same for the front and back internal planes
@@ -68,9 +260,8 @@ if [ "${3:-false}" = true ]; then
     surfaceTransformPoints -translate "(-60 0 -0.25)" -rollPitchYaw "(0 ${2:-0} 0)" constant/triSurface/backInternalWall.stl constant/triSurface/backInternalWall.stl > /dev/null
 fi
 
-# The refinement boxes are rotated according to the fourth argument passed to the script: if no parameter is passed, the default value is false
-echo "The refinement boxes are rotated: ${4:-false}"
-sed -i "s/REFINEMENT_BOXES_ROTATION_FLAG_PLACEHOLDER/${4:-false}/g" "0.orig/include/angulationParameters"
+
+# ----------------------------* ACTUALLY RUN THE CODE *--------------------------
 
 #Create the results directory if it does not exist
 mkdir -p results
diff --git a/simulation/Allrun_autoangle b/simulation/Allrun_autoangle
--- a/simulation/Allrun_autoangle
+++ b/simulation/Allrun_autoangle
@@ -28,28 +28,48 @@ cp -f \
     "$FOAM_RUN"/freight_train_CFD/objects/backInternalWall.stl \
     constant/triSurface/
 
-# Define the maximum rotation angle to be used for the simulation
-# If no parameters are passed, the default value for the angle is 0
-echo "The maximum angle is ${1:-20}"
+# Define some default values
+angle_value="10"
+angle_delta="3"
+gallery_included="false"
+rotated_refinement="false"
 
-# Define the delta to be used for the sequence of simulations
-# If no parameters are passed, the default value for the delta is 3
-echo "The delta is ${2:-3}"
+# Parse the arguments passed to the script
+while getopts "v:d:go" opt; do
+  case $opt in
+    v) angle_value="$OPTARG"
+    ;;
+    d) angle_delta="$OPTARG"
+    ;;
+    g) gallery_included="true"
+    ;;
+    o) rotated_refinement="true"
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
 
-# Define whether the gallery is included in the simulation
-# If no parameters are passed, the default value for the flag is false
-echo "The gallery is included in the simulation: ${3:-false}"
+if [[ $angle_value == "0"  ]]; then
+  echo "Error - The angle value is 0. Please set the angle value to a value greater than 0."
+  exit 1
+fi
 
-# Define whether the refinement boxes are rotated
-# If no parameters are passed, the default value for the flag is false
-echo "The refinement boxes are rotated: ${4:-false}"
+if [[ $angle_delta == "0"  ]]; then
+  echo "Error - The angle delta is 0. Please set the angle delta to a value greater than 0."
+  exit 1
+fi
 
+echo "The maxium angle is $angle_value"
+echo "The angle delta is $angle_delta"
+echo "The gallery is included in the simulation: $gallery_included"
+echo "The refinement boxes are rotated: $rotated_refinement"
 
 
 # Change the value progressively from 0 to MAX_ANGLE by DELTA units. For each value, run the simulation and store the results into 
 # a folder named after the value of the angle (results/results_xxx, where xxx is the value of the angle)
 angle=0
-while [ $angle -le ${1:-10} ];do
+while [ $angle -le $angle_value ];do
     echo "Running the simulation with angle $angle"
     
     # Create the folder for the results
@@ -59,14 +79,14 @@ while [ $angle -le ${1:-10} ];do
     # Replace the placeholders in the angulationParameters_0 file with the value actual value and save the result in the angulationParameters file
     sed "s/ANGULATION_ANGLE_PLACEHOLDER/$angle/g" "0.orig/include/angulationParameters_0"> \0.orig/include/angulationParameters
     sed -i "s/ANGULATION_FLAG_PLACEHOLDER/true/g" "0.orig/include/angulationParameters" 
-    sed -i "s/GALLERY_FLAG_PLACEHOLDER/${3:-false}/g" "0.orig/include/angulationParameters"
-    sed -i "s/REFINEMENT_BOXES_ROTATION_FLAG_PLACEHOLDER/${4:-false}/g" "0.orig/include/angulationParameters"
+    sed -i "s/GALLERY_FLAG_PLACEHOLDER/$gallery_included/g" "0.orig/include/angulationParameters"
+    sed -i "s/REFINEMENT_BOXES_ROTATION_FLAG_PLACEHOLDER/$rotated_refinement/g" "0.orig/include/angulationParameters"
 
     # Rotate the box_galleria.stl file by an angle specified in the 0.orig/include/angulationParameters file along the y axis (also translate the box_galleria.stl file to the origin)
     # Also suppress the output of the surfaceTransformPoints command
     # Do all this only if the gallery is included in the simulation
 
-    if [ "${3:-false}" = true ]; then
+    if [ "$gallery_included" = true ]; then
         surfaceTransformPoints -translate "(-0.5 0 -0.25)" -rollPitchYaw "(0 ${2:-0} 0)" constant/triSurface/box_galleria.stl constant/triSurface/box_galleria.stl > /dev/null
 
         # Do the same for the front and back internal planes
@@ -110,7 +130,7 @@ while [ $angle -le ${1:-10} ];do
     runApplication reconstructPar -latestTime 
 
     # Increase the angle by DELTA
-    angle=$(( $angle + ${2:-3} ))
+    angle=$(( $angle + $angle_delta ))
 
     # Move all the log files to the results directory
     mv log.* results/results_$angle
